### ISSUE TITLE
Help locating the recommended data file

### ISSUE THREAD

**Issue by sourcesync** [Rich-Hall/sentinel1decoder#6]
Hi, thanks for this project.

I'm having trouble locating the recommended data file "S1A_S3_RAW__0SDH_20220710T213600_20220710T213625_044043_0541DB_56CE" at https://dataspace.copernicus.eu/.

Can you recommend an alternate location or possibly another file that will work with your code?

Thanks.

**Comment by Rich-Hall** [comment]
Hi there! Any stripmap data product will do. The new copernicus site has some improved ways to do this - you can search for SM products directly with this option:
![image](https://github.com/user-attachments/assets/50776eb6-2259-4b89-9a87-86b44d7dbc24)

Here's a recent product from the vicinity of Sao Paulo - `S1A_S6_RAW__0SDV_20241113T214410_20241113T214441_056541_06EEC2_F5D0`
